version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: estoque_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Lulumysql30*
      MYSQL_DATABASE: estoque_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:16
    container_name: faturamento_postgres
    environment:
      POSTGRES_PASSWORD: LU5830mar03-
      POSTGRES_DB: faturamento_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  postgres_data:

